### POST request to sign up a user.
POST http://localhost:3000/api/v1/auth/signup
Content-Type: application/json

{
  "email": "mvgSampleEmail1@gmail.com",
  "password": "ABCD@1234"
}


### POST request to login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "mvgSampleEmail1@gmail.com",
  "password": "ABCD@1234"
}